-- AlterTable
ALTER TABLE "User" ADD COLUMN     "quotaPeriod" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "tokenQuota" INTEGER NOT NULL DEFAULT 100000,
ADD COLUMN     "tokensUsed" INTEGER NOT NULL DEFAULT 0;
